 INSERT INTO user
	(username, name)
	VALUES
	('user3123','Fenix Xia'),
	('user02','Steven Paul'),
	('user14','Alice Zahora'),
	('user7','Cloud Strife'),
	('user77','Zack Fair'),
	('user520','Wei Wuxian'),
	('user1314520','Lan Wangji'),
	('user2008','Tony Stark'),
	('user2009','Arthur Pendragon'),
	('user777','Sephiroth');

-- Inserts for song data 

INSERT INTO song
	(title, artist)
	VALUES
	('No Promises to Keep','Loren Allred'),
	('Standing Next to You','Jungkook'),
	('Dance Dance','Day6'),
	('WuJi', 'Xiao Zhan, Wang Yibo'),
	('House of Cards','BTS'),
	('Wake Me Up','Avicii'),
	('Unity','Alan Walker'),
	('The Coconut Song','The San Miguel Master Chorale'),
	('Too Sad to Dance','Jungkook'),
	('Save a Horse','Big & Rich'),
-- 
	("We Didn't Start the Fire",'Billy Joel'),
	('Bohemian Rhapsody','Queen'),
	('Uptown Girl','Billy Joel'),
	('Piano Man', 'Billy Joel'),
	('Careless Whisper','George Michael'),
	('Wake Me Up Before You Go-Go','Wham!'),
	("Don't Go Breaking My Heart",'Elton John, Keke Dee'),
	('Take Me Home, Country Roads','John Denver'),
	("Don't Stop Believin'",'Journey'),
	('Hotel California','Eagles'),
	('We Are The Champions','Queen'),
	('Dancing Queen','ABBA'),
	('Sweet Caroline','Neil Diamond'),
-- Fenix
	('Blinding Lights','The Weeknd'),
	('Youngblood','5 Seconds of Summer'),
	('Misery','Maroon 5'),
	('Grenade', 'Bruno Mars'),
	('Summer', 'Calvin Harris'),
	('Counting Stars', 'OneRepublic'),
	('Chandelier', 'Sia');

-- Inserts for karaokeFile data 

INSERT INTO karaokeFile 
	(version, title)
	VALUES
	('Full','No Promises to Keep'),
	('Short (Loveless Ver.)','No Promises to Keep'),
	('Solo','Standing Next to You'),
	('Duet (Usher Ver.)','Standing Next to You'),
	('Full','Dance Dance'),
	('Full','WuJi'),
	('Full','House of Cards'),
	('Full','Wake Me Up'),
	('Full','Unity'),
	('Full','The Coconut Song'),
	('Full','Too Sad to Dance'),
	('Full','Save a Horse'),
-- 
	('Full',"We Didn't Start the Fire"),
	('Duet','Bohemian Rhapsody'),
	('Full','Bohemian Rhapsody'),
	('Full','Uptown Girl'),
	('Full','Piano Man'),
	('Full','Careless Whisper'),
	('Full','Wake Me Up Before You Go-Go'),
	('Duet (Full)',"Don't Go Breaking My Heart"),
	('Solo (Elton Only)',"Don't Go Breaking My Heart"),
	('Solo (Keke Only)',"Don't Go Breaking My Heart"),
	('Full','Take Me Home, Country Roads'),
	('Full',"Don't Stop Believin'"),
	('Duet',"Don't Stop Believin'"),
	('Full','Hotel California'),
	('Full','We Are The Champions'),
	('Full','Dancing Queen'),
	('Full','Sweet Caroline'),
-- Fenix
	('Full', 'Blinding Lights'),
	('Full', 'Youngblood'),
	('Full', 'Misery'),
	('Full', 'Grenade'),
	('Full', 'Summer'),
	('Full', 'Counting Stars'),
	('Full', 'Chandelier');
	

-- Inserts for contributor data 

INSERT INTO contributor
	(name)
	VALUES
	('Loren Allred'),
	('Nobuo Uematsu'),
	('Jungkook'),
	('Jon Bellion'),
	('Cirkut'),
	('Young K'),
	('Jae'),
	('Sungjin'),
	('Wonpil'),
	('Dowoon'),
	('Xiao Zhan'),
	('Wang Yibo'),
	('Lin Hai'),
	('Jin'),
	('Jimin'),
	('V'),
	('Slow Rabbit'),
	('Aloe Blacc'),
	('Tim Berg'),
	('The Walkers'),
	('Alan Walker'),
	('Kappador'),
	('Ryan Cayabyab'),
	('David Stewart'),
	('Big Kenny'),
	('John Rich'),
	('Paul Worley'),
--
	('Mick Jones'),
	('Billy Joel'),
	('Freddie Mercury'),
	('Roy Thomas Baker'),
	('Brian May'),
	('John Deacon'),
	('Roger Taylor'),
	('Phil Ramone'),
	('Michael Stewart'),
	('George Michael'),
	('Andrew Ridgeley'),
	('Elton John'),
	('Keke Dee'),
	('Gus Dudgeon'),
	('John Denver'),
	('Taffy Nivert'),
	('Bill Danoff'),
	('Jonathan Cain'),
	('Steve Perry'),
	('Neal Schon'),
	('Gregg Rolie'),
	('George Tickner'),
	('Ross Valory'),
	('Prairie Prince'),
	('Don Felder'),
	('Don Henley'),
	('Glenn Frey'),
	('Bernie Leadon'),
	('Benny Andersson'),
	('Björn Ulvaeus'),
	('Stig Anderson'),
	('Agnetha Fältskog'),
	('Anni-Frid Lyngstad'),
	('Neil Diamond'),
	('Tommy Cogbill'),
-- Fenix
	('The Weeknd'),
	('Oscar Holter'),
	('Max Martin'),
	('Luke Hemmings'),
	('Calum Hood'),
	('Ashton Irwin'),
	('Michael Clifford'),
	('Adam Levine'),
	('James Valentine'),
	('PJ Morton'),
	('Bruno Mars'),
	('The Smeezingtons'),
	('Calvin Harris'),
	('Ryan Tedder'),
	('Zach Filkins'),
	('Drew Brown'),
	('Brent Kutzle'),
	('Eddie Fisher'),
	('Sia');

-- Inserts for contribution data 

INSERT INTO contribution
	(contributorName, title, contrType)
	VALUES
	('Loren Allred','No Promises to Keep','Singer'),
	('Nobuo Uematsu','No Promises to Keep','Composer'),
	('Jungkook','Standing Next to You','Singer'),
	('Jon Bellion','Standing Next to You','Writer'),
	('Cirkut','Standing Next to You','Producer'),
	('Young K','Dance Dance','Singer'),
	('Jae','Dance Dance','Singer'),
	('Sungjin','Dance Dance','Singer'),
	('Wonpil','Dance Dance','Singer'),
	('Dowoon','Dance Dance','Drummer'),
	('Xiao Zhan','WuJi','Singer'),
	('Wang Yibo','WuJi','Singer'),
	('Lin Hai','WuJi','Composer'),
	('Jin','House of Cards','Singer'),
	('Jimin','House of Cards','Singer'),
	('V','House of Cards','Singer'),
	('Jungkook','House of Cards','Singer'),
	('Slow Rabbit','House of Cards','Producer'),
	('Aloe Blacc','Wake Me Up','Singer'),
	('Tim Berg','Wake Me Up','Producer'),
	('The Walkers','Unity','Perfomer'),
	('Alan Walker','Unity','Composer'),
	('Kappador','The Coconut Song','Singer'),
	('Ryan Cayabyab','The Coconut Song','Writer'),
	('Jungkook','Too Sad to Dance','Singer'),
	('David Stewart','Too Sad to Dance','Producer'),
	('Big Kenny','Save a Horse','Singer'),
	('John Rich','Save a Horse','Singer'),
	('Paul Worley','Save a Horse','Producer'),
--
	('Mick Jones', "We Didn't Start the Fire", 'Producer'),
	('Billy Joel', "We Didn't Start the Fire", 'Singer'),
	('Freddie Mercury', 'Bohemian Rhapsody', 'Singer'),
	('Roy Thomas Baker', 'Bohemian Rhapsody', 'Producer'),
	('Brian May', 'Bohemian Rhapsody', 'Guitar'),
	('John Deacon', 'Bohemian Rhapsody', 'Bass'),
	('Roger Taylor', 'Bohemian Rhapsody', 'Drums'),
	('Freddie Mercury', 'We Are The Champions', 'Singer'),
	('Brian May', 'We Are The Champions', 'Guitar'),
	('John Deacon', 'We Are The Champions', 'Bass'),
	('Roger Taylor', 'We Are The Champions', 'Drums'),
	('Phil Ramone', "Uptown Girl", 'Producer'),
	('Billy Joel', "Uptown Girl", 'Singer'),
	('Michael Stewart', "Piano Man", 'Producer'),
	('Billy Joel', "Piano Man", 'Singer'),
	('George Michael', "Careless Whisper", 'Singer'),
	('Andrew Ridgeley', "Careless Whisper", 'Writer'),
	('George Michael', "Wake Me Up Before You Go-Go", 'Singer'),
	('Andrew Ridgeley', "Wake Me Up Before You Go-Go", 'Writer'),
	('Elton John', "Don't Go Breaking My Heart", 'Singer'),
	('Keke Dee', "Don't Go Breaking My Heart", 'Singer'),
	('Gus Dudgeon', "Don't Go Breaking My Heart", 'Producer'),
	('John Denver', 'Take Me Home, Country Roads', 'Singer'),
	('Taffy Nivert', 'Take Me Home, Country Roads', 'Writer'),
	('Bill Danoff', 'Take Me Home, Country Roads', 'Writer'),
	('Jonathan Cain', "Don't Stop Believin'", 'Writer'),
	('Steve Perry', "Don't Stop Believin'", 'Writer'),
	('Neal Schon', "Don't Stop Believin'", 'Writer'),
	('Gregg Rolie', "Don't Stop Believin'", 'Vocals'),
	('George Tickner', "Don't Stop Believin'", 'Guitar'),
	('Ross Valory', "Don't Stop Believin'", 'Bass'),
	('Prairie Prince', "Don't Stop Believin'", 'Drummer'),
	('Don Felder', 'Hotel California', 'Writer'),
	('Don Henley', 'Hotel California', 'Writer'),
	('Glenn Frey', 'Hotel California', 'Writer'),
	('Bernie Leadon', 'Hotel California', 'Vocals'),
	('Benny Andersson', 'Dancing Queen', 'Writer'),
	('Björn Ulvaeus', 'Dancing Queen', 'Writer'),
	('Stig Anderson', 'Dancing Queen', 'Writer'),
	('Agnetha Fältskog', 'Dancing Queen', 'Vocals'),
	('Anni-Frid Lyngstad', 'Dancing Queen', 'Vocals'),
	('Neil Diamond', 'Sweet Caroline', 'Singer'),
	('Tommy Cogbill', 'Sweet Caroline', 'Producer'),
-- Fenix
	('The Weeknd','Blinding Lights','Singer'),
	('Oscar Holter','Blinding Lights','Producer'),
	('Max Martin','Blinding Lights','Writer'),
	('Luke Hemmings','Youngblood','Guitarist'),
	('Calum Hood','Youngblood','Bass Guitar'),
	('Ashton Irwin','Youngblood','Drummer'),
	('Michael Clifford','Youngblood','Guitarist'),
	('Adam Levine', 'Misery', 'Singer'),
	('James Valentine', 'Misery', 'Guitarist'),
	('PJ Morton', 'Misery', 'Pianist'),
	('Bruno Mars', 'Grenade', 'Singer'),
	('The Smeezingtons', 'Grenade', 'Producer'),
	('Calvin Harris', 'Summer', 'Singer'),
	('Ryan Tedder', 'Counting Stars', 'Singer'),
	('Zach Filkins', 'Counting Stars', 'Writer'),
	('Drew Brown', 'Counting Stars', 'Guitarist'),
	('Brent Kutzle', 'Counting Stars', 'Bass Guitar'),
	('Eddie Fisher', 'Counting Stars', 'Drummer'),
	('Sia', 'Chandelier', 'Singer');

INSERT INTO signUp 
	(username, id, qType, time, payment)
	VALUES
	('user02', '13', 'p', '01:10:25', '12'),
	('user2008', '7', 'p', '01:11:36', '12'),
	('user1314520', '17', 'p', '21:12:05', '230'),
	('user14', '27', 'p', '13:13:47', '750'),
	('user777', '19', 'p', '05:07:09', '7777'),
	('user02', '29', 'r', '10:13:59', NULL),
	('user7', '3', 'r', '07:12:45', NULL),
	('user3123', '26', 'r', '17:10:13', NULL),
	('user2009', '5', 'r', '23:59:59', NULL),
	('user520', '18', 'r', '13:19:39', NULL);